### ISSUE TITLE
Bug: Using special characters in rounds corrupts botterino.py

### ISSUE THREAD

**Issue by DasherPack** [pgitox/botterino#1]
I created a round, and placed it on rounds.yaml. This is the round in question:

```
horse_13:
  title: "[Horse Series #13] To get the +correct, please give me the coordinates of the structure within 10 meters, and the reason I put it in the horse series"
  url: https://i.imgur.com/X4ZWyxV.jpg
  answer: 40.34199957929391, -1.1080692905623242
  tolerance: 10.0
  manual: true
  after: "Intended SP: discovering that this thing is a `mudéjar` building"
```

I run botterino through windows terminal and it crashed.

I tried to run botterino.py directly and it didn't work. My best guess is that the round got corrupted.

Then, I enabled debug mode to see what was happening, and got a message, like "Do you want to update (Y/N). If I said y, it crashed, and upon restart it would turn debug mode off. If I said no, debug mode turned off.

I'm not sure where to proceed from here. I'm reinstalling the whole botterino.
